/**
 * Bot Service v2.0 — manages bot lifecycle.
 *
 * Features:
 *  - CRUD bots (per-user ownership; admin sees all)
 *  - Start/Stop/Restart with Docker sandbox (preferred) or child_process
 *  - Auto-restart on crash (PM2-like)
 *  - In-memory log ring buffer (last 500 lines) + Socket.IO streaming
 *  - Backward compatible: getBot(id), runCommand(id, cmd), loadPersistedBots()
 *  - Per-user usage limits
 */
const path = require('path');
const fs = require('fs-extra');
const { v4: uuid } = require('uuid');
const { spawn } = require('child_process');
const storage = require('../utils/storage');
const logger = require('../utils/logger');
const dockerSandbox = require('../sandbox/dockerSandbox');

const BOTS_DIR = path.join(__dirname, '..', 'bots');
const TEMPLATES_DIR = path.join(__dirname, '..', 'storage', 'templates');
const META_FILE = 'bots.json';
const MAX_LOGS = 500;

const EXEC_MODE = (process.env.EXECUTION_MODE || 'docker').toLowerCase();
const LIMIT_BOTS_PER_USER = parseInt(process.env.LIMIT_BOTS_PER_USER || '5', 10);

fs.ensureDirSync(BOTS_DIR);
fs.ensureDirSync(TEMPLATES_DIR);

// runtime state: id -> { meta, logs[], status, container?, child?, restarts }
const runtime = new Map();

// ── Persistence ───────────────────────────────────────────────
function loadMeta() { return storage.read(META_FILE, []); }
function saveMeta() {
  const list = [...runtime.values()].map(r => r.meta);
  storage.write(META_FILE, list);
}

function emitLog(botId, line) {
  const r = runtime.get(botId);
  if (!r) return;
  const entry = { ts: Date.now(), line };
  r.logs.push(entry);
  if (r.logs.length > MAX_LOGS) r.logs.shift();
  if (global.io) global.io.to(`bot:${botId}`).emit('bot:log', { botId, ...entry });
}

function emitStatus(botId, status) {
  const r = runtime.get(botId);
  if (!r) return;
  r.meta.status = status;
  if (global.io) global.io.to(`bot:${botId}`).emit('bot:status', { botId, status });
  if (global.io) global.io.to('bots').emit('bots:update', publicMeta(r.meta));
  saveMeta();
}

function publicMeta(m) {
  const { ...rest } = m;
  return rest;
}

// ── Templates ─────────────────────────────────────────────────
function getTemplates() {
  // Built-in templates if folder empty
  return [
    { id: 'whatsapp', name: 'WhatsApp Bot (Baileys)', description: 'Baileys-based WhatsApp bot starter', entry: 'index.js' },
    { id: 'telegram', name: 'Telegram Bot', description: 'node-telegram-bot-api starter', entry: 'index.js' },
    { id: 'discord', name: 'Discord Bot', description: 'discord.js starter', entry: 'index.js' },
    { id: 'custom',  name: 'Empty (Custom)', description: 'Empty index.js', entry: 'index.js' },
  ];
}

function scaffoldTemplate(botDir, tmpl) {
  fs.ensureDirSync(botDir);
  const pkg = {
    name: path.basename(botDir),
    version: '1.0.0',
    main: 'index.js',
    scripts: { start: 'node index.js' },
    dependencies: {},
  };
  let entry = `// ${tmpl} bot — generated by Nell VPS Panel v2.0\nconsole.log("Hello from ${tmpl} bot");\n`;
  if (tmpl === 'whatsapp') {
    pkg.dependencies = { '@whiskeysockets/baileys': '^6.7.0', pino: '^9.0.0' };
    entry = `// WhatsApp Baileys bot starter\nconsole.log("Run 'npm install' first, then edit index.js");\n`;
  } else if (tmpl === 'telegram') {
    pkg.dependencies = { 'node-telegram-bot-api': '^0.66.0' };
    entry = `// Telegram bot starter\n// const TelegramBot = require('node-telegram-bot-api');\n// const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, { polling: true });\nconsole.log('Set TELEGRAM_TOKEN env var');\n`;
  } else if (tmpl === 'discord') {
    pkg.dependencies = { 'discord.js': '^14.15.0' };
    entry = `// Discord bot starter\nconsole.log('Discord bot ready');\n`;
  }
  fs.writeFileSync(path.join(botDir, 'package.json'), JSON.stringify(pkg, null, 2));
  fs.writeFileSync(path.join(botDir, 'index.js'), entry);
}

// ── CRUD ──────────────────────────────────────────────────────
function listBots(user) {
  const all = [...runtime.values()].map(r => r.meta);
  if (!user || user.role === 'admin') return all;
  return all.filter(b => b.ownerId === user.id);
}

function getBot(id) {
  const r = runtime.get(id);
  return r ? { ...r.meta, logs: r.logs.slice(-100) } : null;
}

function createBot({ name, type, entry, template, ownerId }) {
  // Per-user limit
  const owned = [...runtime.values()].filter(r => r.meta.ownerId === ownerId).length;
  if (owned >= LIMIT_BOTS_PER_USER) {
    const err = new Error(`Bot limit reached (${LIMIT_BOTS_PER_USER} per user)`);
    err.status = 403; throw err;
  }
  const id = uuid();
  const dir = path.join(BOTS_DIR, id);
  scaffoldTemplate(dir, template || type || 'custom');
  const meta = {
    id, name, type: type || 'custom', entry: entry || 'index.js',
    ownerId, status: 'stopped', autoRestart: true, restarts: 0,
    createdAt: new Date().toISOString(),
  };
  runtime.set(id, { meta, logs: [], child: null, container: null });
  saveMeta();
  return meta;
}

function updateBot(id, patch) {
  const r = runtime.get(id);
  if (!r) return null;
  Object.assign(r.meta, patch);
  saveMeta();
  return r.meta;
}

async function deleteBot(id) {
  const r = runtime.get(id);
  if (!r) return false;
  await stopBot(id).catch(() => {});
  runtime.delete(id);
  const dir = path.join(BOTS_DIR, id);
  await fs.remove(dir).catch(() => {});
  saveMeta();
  return true;
}

// ── Lifecycle ─────────────────────────────────────────────────
async function startBot(id) {
  const r = runtime.get(id);
  if (!r) throw Object.assign(new Error('Bot not found'), { status: 404 });
  if (r.meta.status === 'running') return r.meta;

  const botDir = path.join(BOTS_DIR, id);
  fs.ensureDirSync(botDir);
  emitStatus(id, 'starting');
  emitLog(id, `[panel] Starting bot (${EXEC_MODE} mode)`);

  const onLog = (line) => emitLog(id, line);
  const onExit = (code) => {
    emitLog(id, `[panel] Bot exited with code ${code}`);
    r.container = null; r.child = null;
    if (r.meta.autoRestart && code !== 0 && r.meta.status !== 'stopping') {
      r.meta.restarts = (r.meta.restarts || 0) + 1;
      emitLog(id, `[panel] Auto-restart in 3s (attempt #${r.meta.restarts})`);
      emitStatus(id, 'restarting');
      setTimeout(() => startBot(id).catch(e => emitLog(id, `[panel] Restart failed: ${e.message}`)), 3000);
    } else {
      emitStatus(id, code === 0 ? 'stopped' : 'error');
    }
  };

  if (EXEC_MODE === 'docker' && await dockerSandbox.ping()) {
    try {
      const { container } = await dockerSandbox.startContainer({
        botId: id, botDir, entry: r.meta.entry, onLog, onExit,
      });
      r.container = container;
      emitStatus(id, 'running');
      return r.meta;
    } catch (e) {
      emitLog(id, `[panel] Docker failed: ${e.message}. Falling back to child_process.`);
    }
  }

  // child_process fallback
  const child = spawn('node', [r.meta.entry || 'index.js'], { cwd: botDir, env: { ...process.env } });
  r.child = child;
  child.stdout.on('data', d => d.toString().split(/\r?\n/).forEach(l => l && onLog(l)));
  child.stderr.on('data', d => d.toString().split(/\r?\n/).forEach(l => l && onLog(`[err] ${l}`)));
  child.on('exit', code => { r.child = null; onExit(code); });
  emitStatus(id, 'running');
  return r.meta;
}

async function stopBot(id) {
  const r = runtime.get(id);
  if (!r) throw Object.assign(new Error('Bot not found'), { status: 404 });
  emitStatus(id, 'stopping');
  emitLog(id, '[panel] Stopping bot');
  if (r.container) await dockerSandbox.stopContainer(r.container).catch(() => {});
  if (r.child) try { r.child.kill('SIGTERM'); } catch { /* ignore */ }
  r.container = null; r.child = null;
  emitStatus(id, 'stopped');
  return r.meta;
}

async function restartBot(id) {
  await stopBot(id).catch(() => {});
  await new Promise(res => setTimeout(res, 500));
  return startBot(id);
}

// ── Command runner (npm install etc.) ─────────────────────────
function runCommand(id, command) {
  return new Promise((resolve, reject) => {
    const r = runtime.get(id);
    if (!r) return reject(new Error('Bot not found'));
    const botDir = path.join(BOTS_DIR, id);
    // Whitelist safe commands only
    const SAFE = /^(npm|node|yarn|pnpm|ls|cat|pwd|echo)\b/;
    if (!SAFE.test(command.trim())) return reject(new Error('Command not allowed'));
    emitLog(id, `[cmd] $ ${command}`);
    const child = spawn(command, { cwd: botDir, shell: true });
    let out = '';
    child.stdout.on('data', d => { const s = d.toString(); out += s; s.split(/\r?\n/).forEach(l => l && emitLog(id, `[cmd] ${l}`)); });
    child.stderr.on('data', d => { const s = d.toString(); out += s; s.split(/\r?\n/).forEach(l => l && emitLog(id, `[cmd] ${l}`)); });
    child.on('exit', code => { emitLog(id, `[cmd] exit ${code}`); resolve({ code, output: out.slice(-4000) }); });
  });
}

// ── Persistence on boot ───────────────────────────────────────
function loadPersistedBots() {
  const meta = loadMeta();
  meta.forEach(m => {
    runtime.set(m.id, { meta: { ...m, status: 'stopped' }, logs: [], child: null, container: null });
  });
  logger.info(`Loaded ${meta.length} persisted bots`);
}

module.exports = {
  // v2 API
  listBots, getBot, createBot, updateBot, deleteBot,
  startBot, stopBot, restartBot, runCommand,
  loadPersistedBots, getTemplates,
  // expose for advanced use
  BOTS_DIR,
};
